#############################################################################
# Makefile for building: ./SpeedReader.js
# Generated by qmake (3.1) (Qt 6.5.3)
# Project:  ../SpeedReader.pro
# Template: app
# Command: /home/florin/Qt/6.5.3/gcc_64/bin/qmake6 -o Makefile ../SpeedReader.pro -qtconf /home/florin/Qt/6.5.3/wasm_singlethread/bin/target_qt.conf
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = emcc
CXX           = em++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra $(DEFINES)
INCPATH       = -I../../SpeedReader -I. -I../../../Qt/6.5.3/wasm_singlethread/include -I../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets -I../../../Qt/6.5.3/wasm_singlethread/include/QtGui -I../../../Qt/6.5.3/wasm_singlethread/include/QtCore -I. -I. -I/home/florin/.emscripten_ports/openssl/include -I../../../Qt/6.5.3/wasm_singlethread/mkspecs/wasm-emscripten
QMAKE         = /home/florin/Qt/6.5.3/gcc_64/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/florin/Qt/6.5.3/gcc_64/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /home/florin/Qt/6.5.3/gcc_64/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SpeedReader.js1.0.0
DISTDIR = /home/florin/QtProjects/SpeedReader/build_wa/.tmp/SpeedReader.js1.0.0
LINK          = em++
LFLAGS        = -s 'ASYNCIFY_IMPORTS=qt_asyncify_suspend_js,qt_asyncify_resume_js' -s WASM=1 -s MAX_WEBGL_VERSION=2 -s ERROR_ON_UNDEFINED_SYMBOLS=1 --bind -s FETCH=1 -s MODULARIZE=1 -s EXPORT_NAME=createQtAppInstance -s WASM_BIGINT=1 -O2 -s EXPORTED_RUNTIME_METHODS=UTF16ToString,stringToUTF16,JSEvents,specialHTMLTargets -sALLOW_MEMORY_GROWTH -s INITIAL_MEMORY=50MB /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6BundledFreetype.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6BundledLibpng.a
LIBS          = $(SUBLIBS) /home/florin/Qt/6.5.3/wasm_singlethread/lib/objects-Release/QWasmIntegrationPlugin_resources_1/.rcc/qrc_wasmfonts.cpp.o /home/florin/Qt/6.5.3/wasm_singlethread/lib/objects-Release/QWasmIntegrationPlugin_resources_2/.rcc/qrc_wasmwindow.cpp.o /home/florin/Qt/6.5.3/wasm_singlethread/lib/objects-Release/Gui_resources_1/.rcc/qrc_qpdf.cpp.o /home/florin/Qt/6.5.3/wasm_singlethread/lib/objects-Release/Gui_resources_2/.rcc/qrc_gui_shaders.cpp.o /home/florin/Qt/6.5.3/wasm_singlethread/plugins/platforms/libqwasm.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6OpenGL.a /home/florin/Qt/6.5.3/wasm_singlethread/plugins/iconengines/libqsvgicon.a /home/florin/Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqgif.a /home/florin/Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqico.a /home/florin/Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqjpeg.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6BundledLibjpeg.a /home/florin/Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqsvg.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6Svg.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/objects-Release/Widgets_resources_1/.rcc/qrc_qstyle.cpp.o /home/florin/Qt/6.5.3/wasm_singlethread/lib/objects-Release/Widgets_resources_2/.rcc/qrc_qstyle1.cpp.o /home/florin/Qt/6.5.3/wasm_singlethread/lib/objects-Release/Widgets_resources_3/.rcc/qrc_qmessagebox.cpp.o /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6Widgets.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6Gui.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6BundledHarfbuzz.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6BundledFreetype.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6BundledLibpng.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6Core.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6BundledZLIB.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6BundledPcre2.a -lembind   
AR            = emar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../main.cpp \
		../mainwindow.cpp /home/florin/QtProjects/SpeedReader/build_wa/speedreader.js_plugin_import.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		speedreader.js_plugin_import.o \
		moc_mainwindow.o
DIST          = ../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/spec_pre.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/sanitize.conf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/gcc-base.conf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/clang.conf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/qdevice.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/device_config.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/wasm/emcc_ver.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/qconfig.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_freetype.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_libpng.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_pcre2.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labssettings.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_linguist.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_png_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_tools_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qcertonlybackend.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qgif.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qico.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_quicklintplugin.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qwasm.pri \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qt_functions.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qt_config.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/wasm/wasm.conf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/wasm-emscripten/qmake.conf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/spec_post.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/toolchain.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/default_pre.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/wasm/default_pre.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/resolve_config.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/default_post.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/wasm/wasm.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/warn_on.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/permissions.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qt.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/resources_functions.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/resources.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/moc.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/unix/opengl.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/uic.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qmake_use.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/file_copies.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/testcase_targets.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/exceptions.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/yacc.prf \
		../../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/lex.prf \
		../../SpeedReader.pro ../mainwindow.h ../main.cpp \
		../mainwindow.cpp
QMAKE_TARGET  = SpeedReader.js
DESTDIR       = ./
TARGET        = ./SpeedReader.js


first: all
####### Build rules

./SpeedReader.js: /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6Widgets.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6Gui.a /home/florin/Qt/6.5.3/wasm_singlethread/lib/libQt6Core.a ui_mainwindow.h $(OBJECTS)  apphtml appjs appsvg
	@test -d ./ || mkdir -p ./
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../SpeedReader.pro ../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/spec_pre.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/sanitize.conf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/gcc-base.conf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/clang.conf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/qdevice.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/device_config.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/wasm/emcc_ver.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/qconfig.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_pcre2.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qcertonlybackend.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qgif.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qico.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_quicklintplugin.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qwasm.pri \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qt_functions.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qt_config.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/wasm/wasm.conf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/wasm-emscripten/qmake.conf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/spec_post.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/toolchain.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/default_pre.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/wasm/default_pre.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/resolve_config.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/default_post.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/wasm/wasm.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/warn_on.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/permissions.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qt.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/resources_functions.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/resources.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/moc.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/uic.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qmake_use.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/file_copies.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/exceptions.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/yacc.prf \
		../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/lex.prf \
		../SpeedReader.pro \
		../../../Qt/6.5.3/wasm_singlethread/plugins/platforms/libqwasm.prl \
		../../../Qt/6.5.3/wasm_singlethread/plugins/iconengines/libqsvgicon.prl \
		../../../Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqgif.prl \
		../../../Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqico.prl \
		../../../Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqjpeg.prl \
		../../../Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqsvg.prl \
		../../../Qt/6.5.3/wasm_singlethread/lib/libQt6Widgets.prl \
		../../../Qt/6.5.3/wasm_singlethread/lib/libQt6Gui.prl \
		../../../Qt/6.5.3/wasm_singlethread/lib/libQt6Core.prl
	$(QMAKE) -o Makefile ../SpeedReader.pro -qtconf /home/florin/Qt/6.5.3/wasm_singlethread/bin/target_qt.conf
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/spec_pre.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/sanitize.conf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/gcc-base.conf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/clang.conf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/qdevice.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/device_config.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/wasm/emcc_ver.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/qconfig.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_freetype.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_harfbuzz.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_libjpeg.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_libpng.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_ext_pcre2.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_core.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_example_icons_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_freetype_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_help.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_jpeg_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsanimation.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labssettings.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_linguist.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_linguist_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_network.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_png_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlcore.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlintegration.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_tools_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_lib_zlib_private.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qcertonlybackend.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qgif.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qico.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qjpeg.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qsvg.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_quicklintplugin.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/modules/qt_plugin_qwasm.pri:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qt_functions.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qt_config.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/common/wasm/wasm.conf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/wasm-emscripten/qmake.conf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/spec_post.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/exclusive_builds.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/toolchain.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/default_pre.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/wasm/default_pre.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/resolve_config.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/default_post.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/wasm/wasm.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/warn_on.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/permissions.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qt.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/resources_functions.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/resources.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/moc.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/unix/opengl.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/uic.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/qmake_use.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/file_copies.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/testcase_targets.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/exceptions.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/yacc.prf:
../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/lex.prf:
../SpeedReader.pro:
../../../Qt/6.5.3/wasm_singlethread/plugins/platforms/libqwasm.prl:
../../../Qt/6.5.3/wasm_singlethread/plugins/iconengines/libqsvgicon.prl:
../../../Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqgif.prl:
../../../Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqico.prl:
../../../Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqjpeg.prl:
../../../Qt/6.5.3/wasm_singlethread/plugins/imageformats/libqsvg.prl:
../../../Qt/6.5.3/wasm_singlethread/lib/libQt6Widgets.prl:
../../../Qt/6.5.3/wasm_singlethread/lib/libQt6Gui.prl:
../../../Qt/6.5.3/wasm_singlethread/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../SpeedReader.pro -qtconf /home/florin/Qt/6.5.3/wasm_singlethread/bin/target_qt.conf

qmake_all: FORCE


all: Makefile ./SpeedReader.js

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents ../main.cpp ../mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) *.html *.js *.wasm /home/florin/QtProjects/SpeedReader/build_wa/speedreader.js_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

apphtml: /home/florin/Qt/6.5.3/wasm_singlethread/plugins/platforms/wasm_shell.html
	sed -e s/@APPNAME@/SpeedReader/g /home/florin/Qt/6.5.3/wasm_singlethread/plugins/platforms/wasm_shell.html > /home/florin/QtProjects/SpeedReader/build_wa/SpeedReader.html

appjs: /home/florin/Qt/6.5.3/wasm_singlethread/plugins/platforms/qtloader.js
	cp -f /home/florin/Qt/6.5.3/wasm_singlethread/plugins/platforms/qtloader.js /home/florin/QtProjects/SpeedReader/build_wa

appsvg: /home/florin/Qt/6.5.3/wasm_singlethread/plugins/platforms/qtlogo.svg
	cp -f /home/florin/Qt/6.5.3/wasm_singlethread/plugins/platforms/qtlogo.svg /home/florin/QtProjects/SpeedReader/build_wa

shellfiles: apphtml appjs appsvg

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_apphtml_make_all:
compiler_apphtml_clean:
	-$(DEL_FILE) SpeedReader.html
compiler_appjs_make_all:
compiler_appjs_clean:
	-$(DEL_FILE) qtloader.js
compiler_appsvg_make_all:
compiler_appsvg_clean:
	-$(DEL_FILE) qtlogo.svg
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/data/dummy.cpp
	em++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h ../../../Qt/6.5.3/wasm_singlethread/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../mainwindow.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/QMainWindow \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qmainwindow.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtwidgetsglobal.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtguiglobal.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qglobal.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtversionchecks.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qconfig.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtcore-config.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtconfigmacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtcoreexports.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtpreprocessorsupport.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtnoop.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsystemdetection.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qprocessordetection.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcompilerdetection.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qassert.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtypes.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtclasshelpermacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtversion.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtypeinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontainerfwd.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsysinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qlogging.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qflags.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcompare_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qatomic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbasicatomic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qatomic_cxx11.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qgenericatomic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qconstructormacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qdarwinhelpers.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qexceptionhandling.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qforeach.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtdeprecationmarkers.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qttypetraits.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qfunctionpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qglobalstatic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmalloc.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qminmax.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qnumeric.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qoverload.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qswap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtenvironmentvariables.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtresource.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qttranslation.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qversiontagging.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtgui-config.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtguiexports.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtwidgets-config.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtwidgetsexports.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qwidget.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qwindowdefs.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobjectdefs.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qnamespace.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtmetamacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobject.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstring.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qchar.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearray.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qrefcount.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qarraydata.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qpair.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qarraydatapointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qarraydataops.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontainertools_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qxptype_traits.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearrayalgorithms.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearrayview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringfwd.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/q20type_traits.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringliteral.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringalgorithms.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qanystringview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qutf8stringview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringtokenizer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringbuilder.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qlist.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qhashfunctions.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiterator.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearraylist.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringlist.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qalgorithms.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringmatcher.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcoreevent.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qscopedpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmetatype.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcompare.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qdatastream.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiodevicebase.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qfloat16.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmath.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiterable.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmetacontainer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontainerinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtaggedpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qscopeguard.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobject_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbindingstorage.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmargins.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qaction.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qkeysequence.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qicon.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsize.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpixmap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpaintdevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qrect.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qpoint.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qcolor.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qrgb.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qrgba64.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsharedpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qshareddata.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qimage.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpixelformat.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtransform.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpolygon.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qregion.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qline.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qvariant.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qdebug.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtextstream.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringconverter_base.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontiguouscache.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qshareddata_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qset.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qhash.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qvarlengtharray.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/q20memory.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpalette.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qbrush.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qfont.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qfontmetrics.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qfontinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qsizepolicy.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qcursor.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qbitmap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qevent.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiodevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qurl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qeventpoint.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qvector2d.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qvectornd.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpointingdevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qinputdevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qscreen.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QList \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QObject \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QRect \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QSize \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QSizeF \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/QTransform \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qnativeinterface.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtabwidget.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QTimer \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtimer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbasictimer.h \
		moc_predefs.h \
		../../../Qt/6.5.3/gcc_64/libexec/moc
	/home/florin/Qt/6.5.3/gcc_64/libexec/moc $(DEFINES) --include /home/florin/QtProjects/SpeedReader/build_wa/moc_predefs.h -I/home/florin/Qt/6.5.3/wasm_singlethread/mkspecs/wasm-emscripten -I/home/florin/QtProjects/SpeedReader -I/home/florin/Qt/6.5.3/wasm_singlethread/include -I/home/florin/Qt/6.5.3/wasm_singlethread/include/QtWidgets -I/home/florin/Qt/6.5.3/wasm_singlethread/include/QtGui -I/home/florin/Qt/6.5.3/wasm_singlethread/include/QtCore -I. ../mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../mainwindow.ui \
		../../../Qt/6.5.3/gcc_64/libexec/uic
	/home/florin/Qt/6.5.3/gcc_64/libexec/uic ../mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../main.cpp ../mainwindow.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/QMainWindow \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qmainwindow.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtwidgetsglobal.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtguiglobal.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qglobal.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtversionchecks.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qconfig.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtcore-config.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtconfigmacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtcoreexports.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtpreprocessorsupport.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtnoop.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsystemdetection.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qprocessordetection.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcompilerdetection.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qassert.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtypes.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtclasshelpermacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtversion.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtypeinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontainerfwd.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsysinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qlogging.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qflags.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcompare_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qatomic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbasicatomic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qatomic_cxx11.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qgenericatomic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qconstructormacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qdarwinhelpers.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qexceptionhandling.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qforeach.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtdeprecationmarkers.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qttypetraits.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qfunctionpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qglobalstatic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmalloc.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qminmax.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qnumeric.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qoverload.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qswap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtenvironmentvariables.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtresource.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qttranslation.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qversiontagging.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtgui-config.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtguiexports.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtwidgets-config.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtwidgetsexports.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qwidget.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qwindowdefs.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobjectdefs.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qnamespace.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtmetamacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobject.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstring.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qchar.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearray.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qrefcount.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qarraydata.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qpair.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qarraydatapointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qarraydataops.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontainertools_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qxptype_traits.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearrayalgorithms.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearrayview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringfwd.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/q20type_traits.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringliteral.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringalgorithms.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qanystringview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qutf8stringview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringtokenizer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringbuilder.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qlist.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qhashfunctions.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiterator.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearraylist.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringlist.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qalgorithms.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringmatcher.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcoreevent.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qscopedpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmetatype.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcompare.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qdatastream.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiodevicebase.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qfloat16.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmath.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiterable.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmetacontainer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontainerinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtaggedpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qscopeguard.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobject_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbindingstorage.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmargins.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qaction.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qkeysequence.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qicon.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsize.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpixmap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpaintdevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qrect.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qpoint.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qcolor.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qrgb.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qrgba64.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsharedpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qshareddata.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qimage.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpixelformat.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtransform.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpolygon.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qregion.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qline.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qvariant.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qdebug.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtextstream.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringconverter_base.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontiguouscache.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qshareddata_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qset.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qhash.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qvarlengtharray.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/q20memory.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpalette.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qbrush.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qfont.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qfontmetrics.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qfontinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qsizepolicy.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qcursor.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qbitmap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qevent.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiodevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qurl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qeventpoint.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qvector2d.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qvectornd.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpointingdevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qinputdevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qscreen.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QList \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QObject \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QRect \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QSize \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QSizeF \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/QTransform \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qnativeinterface.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtabwidget.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QTimer \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtimer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbasictimer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/QApplication \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qapplication.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcoreapplication.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qeventloop.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcoreapplication_platform.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qguiapplication.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qinputmethod.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qlocale.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qguiapplication_platform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../main.cpp

mainwindow.o: ../mainwindow.cpp ../mainwindow.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/QMainWindow \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qmainwindow.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtwidgetsglobal.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtguiglobal.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qglobal.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtversionchecks.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qconfig.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtcore-config.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtconfigmacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtcoreexports.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtpreprocessorsupport.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtnoop.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsystemdetection.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qprocessordetection.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcompilerdetection.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qassert.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtypes.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtclasshelpermacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtversion.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtypeinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontainerfwd.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsysinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qlogging.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qflags.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcompare_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qatomic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbasicatomic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qatomic_cxx11.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qgenericatomic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qconstructormacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qdarwinhelpers.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qexceptionhandling.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qforeach.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtdeprecationmarkers.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qttypetraits.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qfunctionpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qglobalstatic.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmalloc.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qminmax.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qnumeric.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qoverload.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qswap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtenvironmentvariables.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtresource.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qttranslation.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qversiontagging.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtgui-config.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtguiexports.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtwidgets-config.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtwidgetsexports.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qwidget.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qwindowdefs.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobjectdefs.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qnamespace.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtmetamacros.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobject.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstring.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qchar.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearray.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qrefcount.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qarraydata.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qpair.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qarraydatapointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qarraydataops.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontainertools_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qxptype_traits.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearrayalgorithms.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearrayview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringfwd.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/q20type_traits.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringliteral.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringalgorithms.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qanystringview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qutf8stringview.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringtokenizer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringbuilder.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qlist.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qhashfunctions.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiterator.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbytearraylist.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringlist.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qalgorithms.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringmatcher.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcoreevent.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qscopedpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmetatype.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcompare.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qdatastream.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiodevicebase.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qfloat16.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmath.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiterable.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmetacontainer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontainerinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtaggedpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qscopeguard.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qobject_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbindingstorage.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmargins.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qaction.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qkeysequence.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qicon.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsize.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpixmap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpaintdevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qrect.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qpoint.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qcolor.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qrgb.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qrgba64.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsharedpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qshareddata.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qimage.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpixelformat.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qtransform.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpolygon.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qregion.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qline.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qvariant.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qdebug.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtextstream.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qstringconverter_base.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qcontiguouscache.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qmap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qshareddata_impl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qset.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qhash.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qvarlengtharray.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/q20memory.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpalette.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qbrush.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qfont.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qfontmetrics.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qfontinfo.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qsizepolicy.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qcursor.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qbitmap.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qevent.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qiodevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qpointer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qurl.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qeventpoint.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qvector2d.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qvectornd.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qpointingdevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qinputdevice.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/qscreen.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QList \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QObject \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QRect \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QSize \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QSizeF \
		../../../Qt/6.5.3/wasm_singlethread/include/QtGui/QTransform \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qnativeinterface.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtWidgets/qtabwidget.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/QTimer \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qtimer.h \
		../../../Qt/6.5.3/wasm_singlethread/include/QtCore/qbasictimer.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../mainwindow.cpp

speedreader.js_plugin_import.o: /home/florin/QtProjects/SpeedReader/build_wa/speedreader.js_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speedreader.js_plugin_import.o /home/florin/QtProjects/SpeedReader/build_wa/speedreader.js_plugin_import.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/SpeedReader/bin || mkdir -p $(INSTALL_ROOT)/opt/SpeedReader/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/SpeedReader/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/SpeedReader/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/SpeedReader/bin/ 


install_js_file: first FORCE
	@test -d $(INSTALL_ROOT)/opt/SpeedReader/bin || mkdir -p $(INSTALL_ROOT)/opt/SpeedReader/bin
	$(QINSTALL_PROGRAM) /home/florin/QtProjects/SpeedReader/SpeedReader.js $(INSTALL_ROOT)/opt/SpeedReader/bin/SpeedReader.js

uninstall_js_file: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/SpeedReader/bin/SpeedReader.js
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/SpeedReader/bin/ 


install: install_target install_js_file  FORCE

uninstall: uninstall_target uninstall_js_file  FORCE

FORCE:

.SUFFIXES:

